### ISSUE TITLE
Can there be a strength based workout plan be added in?

### ISSUE THREAD

**Issue by vitogarciasg** [brodeurlv/fastnfitness#108]
Like a workout based on the percentages of your 1 rep max? And maybe also have some workouts saved in the app to suggest to the users if they don't know what to do.

**Comment by htremura** [comment]
Yes, I feel like some suggested workouts would be an excellent addition. Getting into staying fit, having a pre-built workout would be excellent. A fantastic future feature could be to automatically customize it based on BMI.

**Comment by brodeurlv** [comment]
Thank you guys for your proposal. I've started to work on this items. 
@vitogarciasg proposal is similar to Guided sessions #30
@htremura proposal is similar to Suggestion: Include library of exercises #79

Don't hesitate to add comments in those issues.  Thank you for taking the time.
I'm closing this thread as a duplicate.
