### ISSUE TITLE
Feature Request: Adding support for music on external storage / SD card

### ISSUE THREAD

**Issue by BeatLink** [brodeurlv/fastnfitness#112]
Recent android versions require an external storage API to access files on external storage or SD card. Would it be possible to implement this API for the music player file browser so that music files on the SD card can be played?

**Comment by brodeurlv** [comment]
Hi Beatlink, I didn't know about that.
I'll see what are the consequences of this new api. I hope it's not too
heavy to implement!

**Comment by brodeurlv** [comment]
Hi @BeatLink , this might be fixed in the 0.19.1 but not sure this is what you were referring to. Can you let me know?
Thanks.

**Comment by BeatLink** [comment]
It works great! Thanks!
