### ISSUE TITLE
Feature Request: Rename category "Bodybuilding" to "Strength"

### ISSUE THREAD

**Issue by senpl** [brodeurlv/fastnfitness#117]
Found in version: 0.18.10

Current behavior: Current Category name "Bodybuilding" is to narrow. Rename to strength would allow to include all kind of weight and strength exercises. Current name suggest only bodybuilding exercises.

Expected behavior: Rename category "Bodybuilding" to "Strength" or "Weight"(less prefered coz Strength seem to more broad).

Step to reproduce:
Edit exercises

**Comment by brodeurlv** [comment]
Thanks for the feedback. That make sense. I'll include that in next release.
