### ISSUE TITLE
No measurement on profile "Size"

### ISSUE THREAD

**Issue by rendeko** [brodeurlv/fastnfitness#118]
Found in version: 0.18.10

Current behavior: Go to profile. Size is purely a numerical input. User is unsure of what to input.

Expected behavior: Size should be lead by (cm), (m), or some sort of measurement for ease of use.

Step to reproduce: Using 0.18.10

**Comment by brodeurlv** [comment]
Thanks for the remark. I'll add the unit in next release. It is supposed to
be in meter as it is used in the BMI index.

**Comment by brodeurlv** [comment]
erratum, it is in cm.

**Comment by brodeurlv** [comment]
Partially fixed in 0.18.11.

**Comment by brodeurlv** [comment]
Now it is completely fixed. :)
