### ISSUE TITLE
Feature request: Move code to Kotlin with Cleanup

### ISSUE THREAD

**Issue by senpl** [brodeurlv/fastnfitness#119]
Found in version: 0.17.3

Current behavior:
Current official android language is Kotlin. Change to Kotlin should not be problematic and the sooner the better. Of course code in java will work so no change in old files is needed. Only project gradle files. Still some code cleanup could be nice.
Expected behavior:
Make project kotlin project. So new language features/libraries could be used.

P.S.
It would also be nice to project start to build in Gradle from start.

**Comment by brodeurlv** [comment]
Hi @senpl

Could you please be more specific about the cleanup? 
You are referring to the 0.17.3 while the current version is 0.18.11 so is the cleanup you are referring to on the 0.17.3 or the 0.18.11?

Also, can you please tell me what you mean by start to "build in Gradle from start". It seems to me that the project is already built with Gradle so maybe I'm misunderstanding what you mean. 
Thanks.

**Comment by senpl** [comment]
Ok. I mean latest version. I just not checked in right place. Code clean up that could go with Kotlin : replace null checks with !! operator. Remove unussed methods from code(Android marks that methods, so if their not used their should be removed). Removed unussed view assings(this is also marked in Android Studio). I would like that new code version would be done in files converted to Kotlin coz this is makes them shorter and easier to read. And with time all files probably should be in Kotlin. I clean up some files in Java format. And I would like to send them in cleaner form. Still removing unussed method in my version should be reviewed coz you might need some of this methods in future.
What I mean build from start is that project should start just after git clone and import from gradle ( Current solution with configuration steps is not that straightforward as it could be.

**Comment by brodeurlv** [comment]
Hi @senpl, 
I'm closing the issue. Kotlin is great but for now the code is in Java. The code will maybe move to Kotlin in the future, but there no point to keep this issue open.
The clean-up thing should be addressed in an independent pull-request. 
Thanks.
