### ISSUE TITLE
Create backlog so important things to do could be prioritize

### ISSUE THREAD

**Issue by senpl** [brodeurlv/fastnfitness#124]
Project lack some sort of backlog. Currently only some TODO in code might indicate what was to be done. It would be practical to create some file with things that could/should be done in project.
I prefer it in english.

**Comment by brodeurlv** [comment]
Hi @senpl, the backlog is this GitHub. Each issue is either a bug or an enhancement. It can be enhanced with labels to show priority for example. 
TODO in the code are usually very small optional things that do not require prioritization. 
Or I could create something like an Asana account to have something separated from this.

**Comment by brodeurlv** [comment]
And in fact, I realize that there is a "Projects" tab in github that could do the job as well.
