### ISSUE TITLE
Feature Request: Limit exercises to specific profile

### ISSUE THREAD

**Issue by BeatLink** [brodeurlv/fastnfitness#125]
Since the quarantine lockdown, I've had to start doing bodyweight exercises since i can no longer go to the gym. It would be really cool if FastNFitness could keep exercises separate to the profile that created it, that way, bodyweight exercises and such could be on one profile, while gym exercises are in another.

**Comment by brodeurlv** [comment]
Thanks @BeatLink for your feedback. 

For what I understand, I think that the best approach to solve your issue would be to add some filters to the exercise list. In the filter,  you could have options to:

- Show only a certain type of exercise (Strength, Cardio, Isometric)
- Show only exercise already used by a profile

That way you would have a reduced list of exercises. 

To give more details, "Profile" have been created for coaches, in order to help them to track their trainees. Limiting the exercise to profiles would be a big issue for them.

**Comment by BeatLink** [comment]
ohh okay! Yeah an exercise filter would be better!

**Comment by alextsakpinis** [comment]
Hello @brodeurlv,
could I work on that issue?

Besides the existing filtering based on the exercise name, I would definitely add an option to allow filtering based on the exercise type (Strength, Cardio, Isometric). I think, this option alone add a lot of value to the user.

I still don't see the value of filtering based on which profile has already used an exercise. Could you elaborate that a bit more please.

**Comment by brodeurlv** [comment]
Hi @alextsakpinis , 

Sure, no problem! Thanks for proposing.
Concerning the filter, there is no need for a filter per profile. I guess that Beatlink wanted to use the profile in a non-standard way like being several profiles of the same person. This is no how the app is made so this doesn't make sense.

Then concerning the filter, there are three places where the filtering per type would be useful:

- The Exercise fragment (accessible from the left menu)
![ExerciseView](https://user-images.githubusercontent.com/16635534/118410921-43912c00-b692-11eb-9109-8745cb92d999.PNG)
- The Exercise selector in the Free Session
![MainView](https://user-images.githubusercontent.com/16635534/118410922-4429c280-b692-11eb-91bd-53e569e08e22.PNG)
- The Exercise selector in the Program Editor page.
![ProgramEditor](https://user-images.githubusercontent.com/16635534/118410923-44c25900-b692-11eb-9719-be2b2768b1f9.PNG)

Let me know if you have any questions.
Thanks

**Comment by alextsakpinis** [comment]
Solved by PR #204.

**Comment by alextsakpinis** [comment]
@brodeurlv this issue can be closed now.

**Comment by brodeurlv** [comment]
Congrats @alextsakpinis for your PR. Thanks.
