### ISSUE TITLE
Suggestion: larger fonts in weight graph

### ISSUE THREAD

**Issue by ddceca** [brodeurlv/fastnfitness#129]
In the weight vs date graph the text is too small. The dates (in the x-axis) and weights (in the y-axis) are quite small, but I can manage to read them (barely). However, the data point labels are almost indistinguishable to me. My phone screen is quite large, that's not the issue.

Perhaps this also applies to the other types of charts, but I've only used the weight monitor so far.

Would it be easy to increase the font size a little bit? Thanks!

**Comment by brodeurlv** [comment]
Hi,
Maybe there is a dependancy with the density of the screen. What is your
phone? Would you mind attaching a screenshot so that I can better
understand how small it is?
Thanks.

**Comment by ddceca** [comment]
Thanks for the quick reply!
My phone's a Xiaomi Mi 9 Lite. It's got a 6.39” screen with a resolution of 1080 x 2340 pixels (403 PPI).
I'm attaching a screen capture and a crappy picture taken with my laptop's webcam.
By the way, it's a chart depicting some body part's measures, so I confirm that the small fonts are present not only in the weight monitor.
![chart screen capture](https://user-images.githubusercontent.com/65789779/83966736-57e27b80-a8bc-11ea-994d-063865ade97b.jpg)
![chart picture](https://user-images.githubusercontent.com/65789779/83966743-5c0e9900-a8bc-11ea-80fe-729b9da9712e.jpg)
