### ISSUE TITLE
Feature request: Sort muscles alphabetically

### ISSUE THREAD

**Issue by har0ke** [brodeurlv/fastnfitness#131]
It would be nice to sort the "Select Muscles" pop-up while editing exercises. 

Is there a reason that glutes are not included in that list?

**Comment by brodeurlv** [comment]
Hi @har0ke, 

Please follow the template and please use words as "Hello" or "Hi" and "Thank you". I'm not a machine. 

Thanks for the feedback anyway. I'll take that into account in the 0.19.1 version.

**Comment by har0ke** [comment]
Hi @brodeurlv, I usually like my issues short and formal, so no offense intended. Sorry for the inconvenience; as of now, I will gladly use your template. Thanks anyway for considering my feature requests.
