### ISSUE TITLE
The "Select Muscles" Pop-up won't reopen

### ISSUE THREAD

**Issue by har0ke** [brodeurlv/fastnfitness#132]
When closing the "Select Muscles" pop-up it won't open a second time. You'd have to re-enter the editing view.

**Comment by brodeurlv** [comment]
Hi har0ke, please follow the template when entering an issue.
I succeed to reproduce the issue as you forgot to mention that you have to save before :

Step to reproduce : 
1. In the Exercise view, click on Muscles

1. Select some muscles

1. Click on the Save button

1. click on Muscles => the dialog doesn't open.

**Comment by brodeurlv** [comment]
Fixed with #130
