### ISSUE TITLE
A few strings not available for translation in version 0.18.11

### ISSUE THREAD

**Issue by rffontenelle** [brodeurlv/fastnfitness#135]
**Describe your issue**
Hello,
I found some strings in the UI that are not available for translation, therefore they are displayed always in English. I found them in Fast N Fitness version 0.18.11 app and in this repository's master branch. Could you please check whether they can be made available for translation?

The strings are:
- "DETAILS" in _Weight monitor_ screen (hardcoded 4 times in [tab_weight.xml](https://github.com/brodeurlv/fastnfitness/blob/9ed830671d97b538aee3a74115daf2835e80e094/app/src/main/res/layout/tab_weight.xml#L61))
- "No chart data available" in e.g. _Body Track_ screen (not from this source code?)
- "Unit settings" in _Settings_ screen (hardcoded in [settings2.xml](https://github.com/brodeurlv/fastnfitness/blob/9ed830671d97b538aee3a74115daf2835e80e094/app/src/main/res/xml/settings2.xml#L3))
- "Light" and "Dark" in theme dialog in _Settings_ screen (flagged translatable=false in [strings.xml](https://github.com/brodeurlv/fastnfitness/blob/9ed830671d97b538aee3a74115daf2835e80e094/app/src/main/res/values/strings.xml#L309))

**To Reproduce**
1. Go to _Weight monitor_ to see one occurrence of "DETAILS" for each box
2. Go to _Settings_ to see "Unit settings" as section heading
3. Go to _Body Track_ to see "No chart data available" (if you have no data, obviously)
4. Go to _Settings_, click _Select your theme_, see "Light" and "Dark"

**Expected behavior**
Be available for translation in values-\<lang>/strings.xml files

**Screenshots**
Not needed I guess? Let me know if needed.

**Desktop (please complete the following information):**
Not needed I guess? Let me know if needed.

**Smartphone:**
 - Device: Samsung Galaxy S9+
 - OS: Android
 - Browser Firefox
 - Version 10

**Additional context**
N/A

**Comment by brodeurlv** [comment]
Hi Rafael, I have addressed your comments and added also other missing translations. 
Please let me know if that's ok and I will publish this version. 
Thanks

**Comment by rffontenelle** [comment]
Besides #137, LGTM!

**Comment by rffontenelle** [comment]
I mean, this issue is solved, so closing.
