### ISSUE TITLE
Research features from OpenTraining to integrate

### ISSUE THREAD

**Issue by BeatLink** [brodeurlv/fastnfitness#144]
Open training seems like another useful workout app. Maybe you could check it out for any features to integrate into fastnfitness https://github.com/EvgenyBatov/opentraining

**Comment by brodeurlv** [comment]
Hi @BeatLink , 

I know this app already. Do you have any more precise information about which features to integrate into fastnfitness ?
As is, this request is neither an issue nor an enhancement request. 
Thanks.

**Comment by BeatLink** [comment]
I'd have to look into it to say XD. My bad! Ill check it out later today

**Comment by BeatLink** [comment]
Just checked out the latest build of FNF and it already seems like it has everything! Ill go ahead and close this :D

**Comment by brodeurlv** [comment]
Ah ah ! Thank you @BeatLink. :)
