### ISSUE TITLE
Rest Timer does not vibrate when complete

### ISSUE THREAD

**Issue by sdriv3r** [brodeurlv/fastnfitness#145]
**Describe your issue**
I have the rest timer turned on for my programs. One thing I have noticed on my phone is that when the countdown reaches 0, it does not vibrate my phone. This only happens when my screen is off. If I leave my screen on, the vibration does work.

I am only reproducing this on my phone (Samsung Galaxy S9+, latest updates). I tried on my tablet (Samsung Tab A 8) and it works fine there, with the screen off or on.

**To Reproduce**
1. Create a program and add exercises that use the rest timer.
2. Go to "Workout" and start a program.
3. Press the checkmark to finish a set and pop the rest timer up.
4. Turn off screen and wait to see if it vibrates.

**Expected behavior**
At the end of the countdown, phone should always vibrate.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy s9+
 - OS: Android 10

**Additional context**
As stated above, only reproduces on my phone and not my tablet. Did not look into why that is the case yet.

**Comment by brodeurlv** [comment]
Yes, there is a weird behavior with the vibration and I realized that this is not always reproductible. On my phone, sometimes is works, sometimes it doesn't. I haven't investigated that much anyway but if you find something, let me know.
Thanks.

**Comment by sdriv3r** [comment]
Hey @brodeurlv,

I looked into this quickly but I'm having issues debugging on my phone (I have the playstore version installed on there and I don't feel like wiping my data to use from AndroidStudio) but I did find something that might be the reason that it works only sometimes. In CountdownDialogbox.java, in the registerAlarm method line 78, we use "set" for the alarmManager. Per android docs:
"Beginning in API 19, the trigger time passed to this method is treated as inexact: the alarm will not be delivered before this time, but may be deferred and delivered some time later..."

Reason I think this might be the problem is because I noticed on my phone that sometimes it vibrates when it's supposed to and gives me 3 zaps(restTime -2), sometimes its late and only gives me a single zap, and sometimes it doesn't happen.

It looks like the better method to use on alarmManager would be setExact: https://developer.android.com/reference/android/app/AlarmManager#setExact(int,%20long,%20android.app.PendingIntent)

Are you set up and have the time to verify this?

**Comment by brodeurlv** [comment]
Hi @sdriv3r , I gave it a try but I'm not sure it is changing anything. 
One of the test I do is that I launch a countdown, then I turn off my screen and I wait, and nothing happens. It is supposed to Wakeup as I use ELAPSED_REALTIME_WAKEUP, but it doesn't work. I wonder if it is not due to the fact that it is launched from a dialog. 
It will need deeper investigation.

**Comment by brodeurlv** [comment]
Hi @sdriv3r , 

> I have the playstore version installed on there and I don't feel like wiping my data to use from AndroidStudio

FYI, with the recent commit from @ironjan , you can have a debug and a release app on the same device. So you should be able to debug this issue more easily on your device. 
Cheers

**Comment by sdriv3r** [comment]
Hi @brodeurlv ,
Problem is when the vibrate gets called in the AlarmReceiver class. I added a "AudioAttribute" to the vibrate and I am able to get it vibrating every time. Both "USAGE_ALARM" and "USAGE_NOTIFICATION" seem to do the job. Reading the doc i'm not sure which one is more appropriate...
https://developer.android.com/reference/android/media/AudioAttributes#USAGE_ALARM

I kind of feel like Notification is a better choice and that Alarm seems a little too "aggressive", but the effect seems the same for our usage.

Will submit a pull request in a little bit.

Cheers
