### ISSUE TITLE
Rest Time Resets to 60s when editing a program

### ISSUE THREAD

**Issue by sdriv3r** [brodeurlv/fastnfitness#146]
**Describe your issue**
When you edit an existing exercise/record in a program, all your current values get copied over to the "Record Editor" except the rest time. That field goes to the default 60s.

When you are editing your program and you have a different rest time ( I use 120s for example), it is easy to open the exercise, change the values you want to increase/decrease (for example, the weight) and forget about the rest time because you intended to keep it the same.

**To Reproduce**
1. Go to "Program List".
2. Select a program that has an exercise with a rest time different than 60s.
3. Edit the exercise (pencil button). Notice that the rest time field is 60s, and not the value that you had before.

**Expected behavior**
I would expect that when you edit the exercise, all the values get copied over to the edit box so that you can change the things you want and keep the rest the same. In other words, if my rest time was 120s, the edit box should keep it at 120s.

**Screenshots**
![Screenshot_20200704-115942_Fast_N_Fitness](https://user-images.githubusercontent.com/30665464/86516600-fe546a80-bdef-11ea-9b0d-57c18a759ec9.jpg)

![Screenshot_20200704-115947_Fast_N_Fitness](https://user-images.githubusercontent.com/30665464/86516603-014f5b00-bdf0-11ea-8a97-e7f85c248d00.jpg)

**Additional context**
Hope I'm not too anoying with all the issues I'm entering. I actually really like the app and find it as good as some of the payed options out there. Also feel free to assign any of these to me, I don't mind at all working on these.

**Comment by brodeurlv** [comment]
Hi @sdriv3r ,
That's a bug ! :) 
As you proposed, I will assign this to you. Thanks. 
Let me know when you can work on this. 0.19.1 is planned for the end of the week so if this is ready, I'll include this issue into it.
Thanks.

**Comment by sdriv3r** [comment]
Hi @brodeurlv ,

Give me 2 days. Should have this one done pretty quickly.

Thanks,
