### ISSUE TITLE
Missing auto-complete in exercise name

### ISSUE THREAD

**Issue by ironjan** [brodeurlv/fastnfitness#147]
**Describe the feature you'd like**
Hello, 
when using the app for the first time, I noticed some peculiarities in the exercise editor. This is applicable to both "free workout" and the program exercise editor.

- 1. **Exercise name should not auto-clear when getting focus** (Moved to  #154)
- 2. **Missing auto-complete**
   * Enter an exercise name. There are no text suggestions - I expected them to be there.
   * Based on the keyboard's look, I assume that `textPasswordVisible` or a similar attribute is used
- 3. **Exercise Editor: "Enter" should move to next EditText** (Moved to #155)

**Describe alternatives you've considered**
I assume that 1. and 2. are per design. However, I'd suggest changing the current behavior as it may be confusing; especially the combination of both is quite annoying at the moment: there is no way to use auto-correct and - if a typo is noticed too late - the name has to be typed in completely anew.

**Additional context**
Feel free to assign this issue to me. However, it may take a while until I can actually work on it ;)

Also, I'm not sure if this issue should be split into three separate ones.

**Comment by brodeurlv** [comment]
Hi @ironjan, thank you for taking the time to open this issue. Usually, 3 issues should be opened for the simple reason that they might not be address at the same time. However looking at your issues, I believe everything can be addressed at once. 
At least 2 and 3 seems straight forward. 
For 1, the best approach would be to have a clearable EditView with a cross at the end of the view to clear if wanted. 

If you want to take care of this, I'm completely ok with it. This seems a very good first contribution and there is no urgency for this topic. Do you have anyway an idea of when you could have the time to work on this ? 
Thanks.

**Comment by ironjan** [comment]
Most likely next weekend or the one after that.

I changed the issue to a task list to track the different parts. 2 & 3 will be straight-forward as you mentioned; 1 will be slightly more effort but should be similarly simple. Most likely each of the changes will be less or equal to 15 lines of code.

**Comment by ironjan** [comment]
@brodeurlv as you might guess from the recent edits and new issues, some parts are more complicated as initially guessed and have been split out. 2/3 are submitted as PRs, #154 is still on my TODO list.
