### ISSUE TITLE
Audible beeps at the end of rest timer

### ISSUE THREAD

**Issue by sdriv3r** [brodeurlv/fastnfitness#159]
**Describe the feature you'd like**
When the rest timer expires, have 3 audible beeps (at the same time as the vibrations). 

I think having the beeps would be more noticeable than the vibrations. Some people dont keep their phone on them and might have it down on the floor, but audible beeps could be heard as long as volume is up or when wearing headphones.

**Describe alternatives you've considered**
If the vibrations get fixed this feature has less importance, but I think it could still be nice to have in either case.

**Additional context**
One thing to consider is if this should be a always on feature or something that can be turned on/off. I think having it always on wouldnt be bad, but i dont feel strongly towards that opinion.

Thank you.

**Comment by brodeurlv** [comment]
Hi @sdriv3r , 

Yes, this would be a good feature. And to answer your last comment, it has to be an option that you can turn on and off because people uses this app in fitness parks and they might not want everyone to hear the 3 bips everytime they do an exercise. :-) And they can't just lower the sound has they might be listening to music too. 
Do you want to take care of this development?

**Comment by sdriv3r** [comment]
Hi @brodeurlv ,

Got it. You can assign it to me. Will put more efforts into the vibration bug and i can tackle this one at the same time.
Thanks,

**Comment by alextsakpinis** [comment]
I am interested in this feature. I would start working on this issue in the upcoming week. Fine for you?

**Comment by brodeurlv** [comment]
Hi Alex, sure, no problem.
Thanks.

**Comment by alextsakpinis** [comment]
Is solved by #197

**Comment by alextsakpinis** [comment]
Should I implement an option to disable/enable the vibration as well? That could be easily done within this PR.

**Comment by brodeurlv** [comment]
Thank you @alextsakpinis.
