### ISSUE TITLE
Incomplete program name in history

### ISSUE THREAD

**Issue by ironjan** [brodeurlv/fastnfitness#171]
**Describe your issue**
Hello, 
in some cases, the program name is incomplete when viewing the history.
Thank you. 
Jan

**To Reproduce**
1. Produce some history for a program called "Standard". The more,the better.
2. Go to history
3. Some entries show the program name as "Stand" or even "S"

**Expected behavior**
All program names should be completely written out.

**Additional context**
App version: 0.19.3

**Comment by brodeurlv** [comment]
Hi @ironjan, what is the size of your screen?
Do you have a snapshot so that I can see precisely the issue? Thanks.

**Comment by ironjan** [comment]
![Screenshot_20200814-002417](https://user-images.githubusercontent.com/1698836/90311087-eb0ce280-def7-11ea-97bc-8aca467260d7.jpg)

5.6", 2.220 x 1.080 px

**Comment by brodeurlv** [comment]
Thanks. So this seems to be very random. I'll try to see what could create
this.

Le sam. 15 août 2020 à 13:06, Jan Lippert <notifications@github.com> a
écrit :
