### ISSUE TITLE
Incomplete History

### ISSUE THREAD

**Issue by ironjan** [brodeurlv/fastnfitness#172]
**Describe your issue**
Hello, 

when I wanted to double-check my training today to update the program, the history was missing ~90% of today's training.

Thank you. 
Jan

**To Reproduce**
1. Start a program, in my case "Standard"
2. Finish exercise `A` with a checkmark
3. Finish exercise `B` with the `X`, e.g. because you did more reps or weights
4. Finish exercise `C` with a checkmark
5. Finish the program
6. Go to history

**Expected behavior**
`A`, `B`, and `C` should show up in history. Only `A` and `C` show up.

**Workaround:**

1. Start a program, in my case "Standard"
2. Finish exercise `A` with a checkmark
3. Finish exercise `B` with the checkmark instead
    1. Click the edit button
    2. Adapt the values to your liking and update the entry
4. Finish exercise `C` with a checkmark
5. Finish the program
6. Go to history

The history is complete.

**Additional context**
App Version 0.19.3

This could also be a user error. I interpreted 
* the checkmark as "everything went as planned",
* the `X` as "did not finish as expected", and
* the trashcan as "don't add to history".

This may be related to #168

**Comment by ExpandingDev** [comment]
It looks like the maintainer fixed this in the latest round of bug fixes, does this persist on the latest version? 0.19.3.1?

https://github.com/brodeurlv/fastnfitness/issues/168

**Comment by brodeurlv** [comment]
Hi guys,
Yes, I guess I fixed it already in the 0.19.3.1.
Can you please check if you still have the issue?
Thanks.

**Comment by ironjan** [comment]
I just checked with 0.19.3.1 and the issue is fixed. However, I had to install by "self-compilation" as 0.19.3.1 is not visible via F-Droid yet.
