### ISSUE TITLE
Updated graph function - view rep count

### ISSUE THREAD

**Issue by Ratatoskor** [brodeurlv/fastnfitness#182]
**Describe the feature you'd like**
Updated graph function that allow user to display number of reps

**Additional context**
Currently for strength exercises it is only possible to track the >=5 reps weight maximum, the 1 rep weight max, or the sum. It would be nice to be able to track the number of reps for bodyweight exercises like pushups & pullups. 

Anything personal you want to add for the developer.
Thanks for the great app!

**Comment by brodeurlv** [comment]
Hi @Ratatoskor, 

Do you mean the max number of Rep per record or the sum of the Rep ? 
For example, if you do 4 times 10 reps, do you want to see 40 on the graph or 10 ? 
Thanks.

**Comment by neitrinoweb** [comment]
Hello @brodeurlv! I highly upvote this feature. 

I think the main problem with graph is that you can only measure weight that you lifted, which is a bit useless option for body weight exercises (like pull-ups, push-ups, abs exercises, etc).
So, I think it would be nice to measure progress in:
1. Total reps  (Like one day you did 3 sets (7-6-5) which would sum in 18 reps at a given day)
2. Max rep at a given day (using previous example 7-6-5 it would be 7)

**Comment by brodeurlv** [comment]
Ok thanks for the details.
I'm working on it.

**Comment by brodeurlv** [comment]
released in 0.19.5
