### ISSUE TITLE
Consider an option to track height in "Body Track" section

### ISSUE THREAD

**Issue by OpenWarp** [brodeurlv/fastnfitness#186]
Hello, 
There is a problem I encounter when using an app to track the kids' and teens' progress. As they continue to grow their height changes considerably over time. And there is no way to track the height along with the weight.

This results in wrong BMI calculations for past periods when the user profile is being updated with the new height. And I have also noticed that the BMI of 16.7 that is perfectly normal for kids is marked "underweight". This should be corrected, and the age is to be taken into account.

As adults typically have no need to track their height except for senior people, while kids and teens do need this feature the proposed solution is to have an option to track height along with the weight shall the user needs this.
Height tracking logically belongs to "Body Track" section but, being able to observe and enter current height in the "Weight Track" section would be a plus. There are people who routinely measure their weight and height, and having those on one page makes sense. 

I believe there a quite a few people in need of this feature.
Thank you for your time and consideration.

**Comment by jimbo8098** [comment]
Excellent idea, I thought it was odd too till I read your use case...

**Comment by brodeurlv** [comment]
Dev ongoing. 
- [x] Migrate Profile size to BodyMeasure
- [ ] Allow graph history view

@OpenWarp, I will split this request in two issues. One for Size, one for BMI.

**Comment by brodeurlv** [comment]
I finally added it to the Weight fragment. The Index are only considering the last measure.
