### ISSUE TITLE
Dates Are Incorrect

### ISSUE THREAD

**Issue by jimbo8098** [brodeurlv/fastnfitness#189]
Hi,

I just downloaded the app and noticed an issue with the dates on the initial age selection screen where, after selecting my date of birth (15/11/1993) using the calendar, the date shown in the field afterwards is 15/12/1993. I've found the same thing happens in the profile page too so I think there may be something wrong with the way the date is being saved to the profile data.

**Smartphone:**
 - Device: OnePlus 3T
 - OS: Android 9, OxygenOS 9.0.6

**Comment by brodeurlv** [comment]
Profile page is fixed in  [cc88f26](https://github.com/brodeurlv/fastnfitness/commit/cc88f26d3d5ee5bb875a38626759941bc331f2a3)
Initial Age selection still to be fixed.
