### ISSUE TITLE
Missing access grant for music player

### ISSUE THREAD

**Issue by brodeurlv** [brodeurlv/fastnfitness#194]
If file access has not been granted before, then the file browser on the music player doesn't show anything. 

**To Reproduce**
1. Fresh install 0.19.5
2. Click on settings, then display player
3. Click on the corner right button, the file browser opens but does provide access to anything interesting. 

**Expected behavior**
The pop up to grant access to file should open as for the profile picture. 

**Screenshots**
None

**Comment by alextsakpinis** [comment]
Since I have worked on the task (Random Play button) which is related to that one, I would continue on that if that is fine for you?

**Comment by brodeurlv** [comment]
Yes sure.Thank you.
You can take example of the code I used for changing the profile picture if
you want.
Thanks.

**Comment by brodeurlv** [comment]
Fixed with PR #196.
