### ISSUE TITLE
Add translation resources on Weblate

### ISSUE THREAD

**Issue by comradekingu** [brodeurlv/fastnfitness#206]
I can help set up the components on Weblate if
https://hosted.weblate.org/user/kingu
is added in
https://hosted.weblate.org/access/fastnfitnesss/#users :)

**Comment by brodeurlv** [comment]
Hi kingu, thanks for proposing. 
I have added you as user. 
Thing is that I haven't setup weblate yet as it is new to me and I didn't have time to search how to set it up. 
If ever you can help me to build things properly, I would appreciate. It would save me probably a lot of time! 😊
Thanks.

**Comment by comradekingu** [comment]
Should work now. You can either add me to the project here, or set up https://docs.weblate.org/no/latest/admin/continuous.html#automatically-receiving-changes-from-github and it should be all good to go.

**Comment by brodeurlv** [comment]
Thank you @comradekingu for setting this up.
