### ISSUE TITLE
Exported records are not selectable when trying to import them

### ISSUE THREAD

**Issue by SpikeShape** [brodeurlv/fastnfitness#210]
Found in version: 0.20.1

Current behavior: When trying to select previously exported data there is no way to select the exported files. They are all grayed out.

Expected behavior: The files are selectable when navigating to the folder the data has been exported to.

Step to reproduce:
1) Select 'Export Records' on phone 1
2) Copy exported records to phone 2
3) Select 'Import Records' on phone 2
4) Navigate to the copied files
--> Files appear as if they where incompatible.

Device: phone 1: Sony Xperia XA2; phone 2: Google Pixel 4a
OS: phone 1: Android 9; phone 2: Android 11
Version 0.20.1 from F-Droid

**Comment by brodeurlv** [comment]
The issue came from the before API.29 devices who did not export with the extension CSV. 
The workaround for current version would be to add the ".csv" extension to the files.
