### ISSUE TITLE
Enable Wiki on Repository

### ISSUE THREAD

**Issue by RyanGreenup** [brodeurlv/fastnfitness#222]
**Describe the feature you'd like**
Hello, 
would it be possible to enable the wiki on this repository?

**Describe alternatives you've considered**
N/A

**Additional context**

I've used [Fitnotes](https://play.google.com/store/apps/details?id=com.github.jamesgay.fitnotes&hl=en_AU&gl=US) in the past and I imported the exercise table to use in *Fast and Fitness* so I thought I would document it here but I can't.

I forked and made a page [here](https://github.com/RyanGreenup/fastnfitness/wiki/Importing-from-other-Applications) to show what I mean.

Thanks!

**Comment by brodeurlv** [comment]
Hi @RyanGreenup , 

I don't understand what you mean by enable the wiki. There is already a wiki page (empty, that's right !)  on Github here : https://github.com/brodeurlv/fastnfitness/wiki
Is there another way to create wiki pages on github ? 

Anyway, thank you for building your page on the migration from fitnotes. This can definitively be helpful.

**Comment by brodeurlv** [comment]
I finally copy paste your page. 
Thanks for your contribution.
