### ISSUE TITLE
Export/Import between 0.20.1 and 0.20.2 broken

### ISSUE THREAD

**Issue by themightyoarfish** [brodeurlv/fastnfitness#224]
**Describe your issue**
I want to move data from one phone (0.20.1, Lineagos 14 with Android 7.1.2 I believe) to a new phone (0.20.2, Lineagos with Android 11). When I Export the data, I get a folder, but when I try to import and navigate to this folder, all files are unselectable.

**To Reproduce**
1. Click three dots at top right
2. Hit `Export records`
3. Move the folder to a new device
4. On new device, click three dots at top right
5. On new device, click `Import Records`
6. On new device, navigate to the exported folder from the old device
7. ???

**Expected behavior**
The `export/` subfolder or its parent is selectable and all data gets imported. Either folders or files therein are selectable

**Screenshots**

![photo_2021-09-17_16-56-55](https://user-images.githubusercontent.com/11613312/133804301-f998b7f9-838c-49a6-85ce-897b99783b7f.jpg)

**Smartphone (please complete the following information):**
 - Device: Moto G4 Plus, Moto G7 Plus
 - OS: Lineageos 14.1, Android 7.1.2 and Lineageos 18.1, Android 11
 - Version 0.20.1 and 0.20.2

**Comment by themightyoarfish** [comment]
Same problem when versions match by the way.

**Comment by brodeurlv** [comment]
Hi @themightyoarfish , 

Yes, there was an issue in the 0.20.1 that has been fixed in the 0.20.2. You can fix your export by adding the extension .csv to your file.

**Comment by themightyoarfish** [comment]
Which file?

**Comment by brodeurlv** [comment]
Sorry, I meant on your files with an S, the files that you are not able to select. Just add ".csv"  and then you will be able to select them.
