### ISSUE TITLE
Records have time of Template creation if set to success using record editor dialog

### ISSUE THREAD

**Issue by hhpmmd** [brodeurlv/fastnfitness#232]
Hi, 
I am pretty sure this is a bug and not intended behavior:
If you start a program and then click the checkmark-button it sets the record-state to success and updates the time of the record to _now_. If you click the edit-button (with the pen icon) you get the record editor dialog and if you press success in that dialog it does not update the time for the record but uses the time of the program creation.

**To Reproduce**
1. Start an **old** program containing two or more entries
2. Click on the checkmark for the first one
3. Click on the pen icon for the second one, then click on success in the dialog
4. The first entry should have the current time, while the second one should have the time of the program creation

**Expected behavior**
Both entries should have the current time.

**Screenshots**
Here the program is created on 1.10.2021, the current date being 30.10.2021.
The red dots are supposed to represent the touches (or just highlight in last screenshot).
![SC1](https://user-images.githubusercontent.com/77058867/139537994-5a160efc-3c0f-43bc-99dd-b952ddc115c8.png)
![SC2](https://user-images.githubusercontent.com/77058867/139538004-5062debe-ca01-41a6-996c-2342bc6946b5.png)
![SC3](https://user-images.githubusercontent.com/77058867/139538007-daa38fa4-abd0-4902-ab1a-c7fcf38c2c8d.png)
![SC4](https://user-images.githubusercontent.com/77058867/139538011-feb91c1f-4e6d-4eb5-bb86-39db5f41c792.png)
![SC5](https://user-images.githubusercontent.com/77058867/139538016-40b65eb6-c1be-4924-9231-cd383dd85400.png)

The screenshots are from running the master branch in the emulator.

**Additional context**
I looked into the code and found that if you click the checkmark you call a function in RecordArrayAdapter (line 330) which updates the time for the record while when you go the edit-dialog route you go through RecordEditorDialogbox (line 150) which doesn't update the time.

I think there are various ways to fix it. I could submit a PR myself, but I think it's best if someone with more insight into the code base-fixes this. But I could do a PR if you want me to.

**Comment by brodeurlv** [comment]
Hi @hhpmmd, 

Thank you for this detailled report. Indeed, it looks like a bug ! Feel free to submit a PR if you like. The fix should have a limited scope and should not impact anything else. Let me know is you have questions. 
Thanks.
