### ISSUE TITLE
v0.20.5.1 not on f-droid

### ISSUE THREAD

**Issue by fabian-thomas** [brodeurlv/fastnfitness#253]
v0.20.5.1 doesn't seem to be on f-droid (yet?) and v0.20.5.0 crashes for me. Can't downgrade either.

Because of such cases it would be nice if the signed apk could be released on github. In best case with the same signing key as the version on f-droid.

**Comment by brodeurlv** [comment]
Hi, Can't you upgrade it from Google play?

**Comment by fabian-thomas** [comment]
Unfortunately no. The google builds are signed with a different key. I tried uninstalling and reinstalling from Play Store but that broke my backups.

Fortunately the update is now available from f-droid, so my issues are resolved.

For the future:
Is there some way to make the apks that are served by fdroid available here on github?
