### ISSUE TITLE
App Fails to Launch on 0.20.5

### ISSUE THREAD

**Issue by brandonp2412** [brodeurlv/fastnfitness#254]
**Describe your issue**
After upgrading to version 0.20.5 the app fails to launch.

**To Reproduce**
1. Install version 0.20.4
2. Upgrade to 0.20.5
3. Try to launch the app

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: LineageOS flame 18

**Additional context**
I ran logcat while launching and found this error:

`02-28 12:27:38.746  9241  9241 E AndroidRuntime: FATAL EXCEPTION: main
02-28 12:27:38.746  9241  9241 E AndroidRuntime: Process: com.easyfitness, PID: 9241
02-28 12:27:38.746  9241  9241 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.easyfitness.DAO.record.Record.getSets()' on a null object reference
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.DAO.DatabaseHelper.copyTemplateValues(DatabaseHelper.java:401)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.DAO.DatabaseHelper.onUpgrade(DatabaseHelper.java:217)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.DAO.DAOBase.getReadableDatabase(DAOBase.java:24)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.DAO.DAOProfile.getProfile(DAOProfile.java:92)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.MainActivity.initActivity(MainActivity.java:1076)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.easyfitness.MainActivity.onStart(MainActivity.java:348)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:8018)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-28 12:27:38.746  9241  9241 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by brodeurlv** [comment]
This is already fixed in  0.20.5.1. Did you upgrade it from Google play?

**Comment by tfbninja** [comment]
I had this same issue on my Pixel 4a running Android 12. I deleted the app and then re-installed it which fixed the crashing issue but then my records were missing and I had to import. Unfortunately they did not import correctly but I messed around with them in excel to get the old records to fit the new pattern. If anyone else has this issue you can email me your records and I'll put them in the new format.
