### ISSUE TITLE
app crashes when adding set with countdown 

### ISSUE THREAD

**Issue by dgmcguire** [brodeurlv/fastnfitness#275]
**Describe your issue**
After last update I can no longer add a set with activate countdown checked.  I.e. I can't use the countdown feature.
Thanks!

**To Reproduce**
1. Check "activate rest countdown"
2. Click add
3. App crashes back to my home screen 

**Expected behavior**
I would expect a countdown timer

**Screenshots**
![Screenshot_20240408-182820](https://github.com/brodeurlv/fastnfitness/assets/1944735/29c6f0a5-ca37-48ff-8ada-8b5f0765da3e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] pixel 7 pro 
 - OS: [e.g. iOS8.1]android
 - Browser [e.g. stock browser, safari] fdroid installed app?
 - Version [e.g. 22] android 14

**Additional context**

**Comment by bust3r** [comment]
I have the same problem. This also happens when I complete a workout with a timer in a defined program.

Device: Samsung Galaxy S10
OS: Android 12
App from f-droid store version 0.20.6

Uninstalling and installing version 0.20.5.1 fixes this.
