### ISSUE TITLE
Fix CVS export

### ISSUE THREAD

**Issue by brodeurlv** [brodeurlv/fastnfitness#31]
Found in version: 0.14.6
Current behavior: Not all data are exported/imported
Expected behavior: All data should be exported/imported

@EGUltraTM, I opened this bug to track your remark on the CVS export.
Did you work on this topic or do you need help to fix this ?

**Comment by EGUltraTM** [comment]
HI,

at the moment im on an business trip for the next 2 weeks. So i cant work on fixing this even if it shouldnt be a big deal at all. If you could fix it it would be nice.
When im back i need to get more into your code and start working with it.

But at the moment im in China and i will fly to America and Spain and then finally back.

**Comment by brodeurlv** [comment]
I'm currently working on a new "profile" page. You will probably be back before I finish. I will let you know if not.

**Comment by brodeurlv** [comment]
Hello,
it is fixed.

**Comment by brodeurlv** [comment]
In 0.15.1.
