### ISSUE TITLE
Renaming of terms (on most of the screens and especially in export)

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#32]
On the Body Building tab and when exporting, some terms should be renamed:

**poids -> weight**
**repetition -> reps**
**serie -> sets**
and maybe: **machine -> exercise** (because then its the same with cardio export? see below)

Same for the profile export:
table, id, poids, date
**poids -> weight**

Why is the order different from the bodybuilding table export? Should be the same: table, id, date, weight

The Cardio export reads:
table, id, date, exercice, duration, distance, profil_id
So there is a spelling mistake:
**exercice -> exercise**

**Comment by geniusupgrader** [comment]
After looking through the source code, there are still many comments and variables in french. For me this is not a problem, but preferable there should be only one language then.

**Comment by brodeurlv** [comment]
hi, thank you very much for all your comments. this is very helpful.
yes you're right. I started the development in French for my personal use and then I decided to make it open source and so more international.
I will update in priority the UI and the export. for the comments it will be based on opportunity.
Would you mind reviewing also the body part for the measures. I'm not sure everything is correct.
thank you.

**Comment by geniusupgrader** [comment]
What do you mean exactly with "body part for the measures".
Do you mean something inside the  "Body Track" fragment?
Or do you mean the units kg/lbs inside the "Body Building" fragment?

**Comment by brodeurlv** [comment]
Yes, I meant the Body Track. In particular, the "Hips".
Thanks.
