### ISSUE TITLE
Revision of Body Track

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#35]
Coming from #32 :

The Body Track needs a revision.

**Comment by geniusupgrader** [comment]
I've tested the functionality and the code of Body Track, but can't find any big mistakes. Where do you think is it not correct, exactly?

**Comment by geniusupgrader** [comment]
Well, the name „behind“ could be just „hips“.

**Comment by brodeurlv** [comment]
Behind vs Hips was indeed my main doubt. I started calling it "behind" and then changed the label. But if nothing is shocking you then that should be fine. Thank you for checking.
