### ISSUE TITLE
Exercise page: Missing functionality to add a new exercise

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#40]
Found in version: 0.15.2

Current behavior: At the exercise page/fragment no new exercise can be added, because it is connected within the BodyBuilding page. And only when adding a new record the actual exercise/machine is recorded as well.

Expected behavior: The exercise page/fragment should be responsible for the management of all exercises. So its natural to add a new exercise there as well. A floating button or something similar should be there and the functionality to add a new exercise for this page and the database.
This design allows to create new exercises at home before the actual training. Also this would work quite well with #30 .

There is some difficulty to implement this, because the „machines“ database (which is better called „exercises“, see #32 ) is not yet exported on its own, but is tangled within BodyBuilding csv export. 
So this also effects exporting and importing.

**Comment by geniusupgrader** [comment]
I will look into this

**Comment by brodeurlv** [comment]
Oh that's great. I'm doing quite a big refactoring on how the records are managed but that should not impact the Exercise part. 
Thanks.

**Comment by geniusupgrader** [comment]
I've added this functionality in #43, maybe you can take a look?

**Comment by brodeurlv** [comment]
So this is fixed ! Thank you for your contribution.
