### ISSUE TITLE
MachineDetailsActivity is not registered in the Manifest

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#41]
Found in version: 0.15.2

Current behavior: MachineDetailsActivity is not registered in the Manifest

Expected behavior: Either it should be registered,
or if it is a parent class it should be make abstract
or it should be deleted.

Step to reproduce:

**Comment by brodeurlv** [comment]
Good catch. It should be deleted. I used it before but I migrated it to a fragment.

**Comment by brodeurlv** [comment]
I removed the file in the last commit.
Thanks.
