### ISSUE TITLE
Image of exercise not taken over

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#45]
Found in version: 0.15.2

Current behavior:
In the Body Building page: When at least two letters in the exercise field (Enter exercise name here) are entered, then a window pops up with the corresponding exercises, which have these letters in their name. When clicking on an exercise with an image, the text is transfered in the exercise field, but the image is not taken over into the round image on the left to the exercise field.
Only when using the list on the right to the exercise field it works.

Expected behavior:
Image should be taken over

Step to reproduce:
Follow instructions above.

**Comment by brodeurlv** [comment]
Hi,
Yes you're right. That's funny because I reallized that yesterday while I
was continuing the merge of cardio and fonte fragment.
This should be fixed with this update.
Thanks.

**Comment by geniusupgrader** [comment]
Nice.
By the way: Good luck with the merge then

**Comment by brodeurlv** [comment]
Fixed in 0.16.
