### ISSUE TITLE
Feature request: filtering/searching for exercises in the exercises page

### ISSUE THREAD

**Issue by geniusupgrader** [brodeurlv/fastnfitness#46]
Found in version: 0.15.2

Current behavior: 
When there are many exercises in the exercises page it is difficult to find the one you're looking for to edit it.

Expected behavior:
So some function for filtering or searching for the exercise page would be nice. I guess, something like the exercise completion from the Body Building page (when typing in the exercise field) is sufficient.

**Comment by brodeurlv** [comment]
Yes you're right that would be nice. Do you think this is something you
could do ?

**Comment by geniusupgrader** [comment]
I've made a Pull Request!

**Comment by geniusupgrader** [comment]
Can you have a look at my updated Pull Request?
