### ISSUE TITLE
Allow to edit Exercise details directly from the BodyBuilding fragment

### ISSUE THREAD

**Issue by brodeurlv** [brodeurlv/fastnfitness#48]
Found in version: 0.15.2

Current behavior: Exercise details can only be edited in Exercise page.

Expected behavior: Could be set directly in the Exercise list by clickinng on the exercise.

**Comment by geniusupgrader** [comment]
Where exactly do you want to click on? If you click inside the text view (Enter exercise name here) you choose another exercise, if you click on the list symbol you get the popup list and when you click an exercise there it get transfered into the text view as well.

Maybe you mean to add another button in each row of the popup list?

I would propose **long clicking**:
So, when long clicking on the text view or on an entry in the popup list, that the corresponding details for this exercise is opened (with correct backtrace -> back to the body building fragment)

**Comment by geniusupgrader** [comment]
I think its ok for now
