### ISSUE TITLE
CSV Export renaming of columns

### ISSUE THREAD

**Issue by brodeurlv** [brodeurlv/fastnfitness#49]
Split of #32 but addressing only CSV. 

Same for the profile export:
table, id, poids, date
poids -> weight

Why is the order different from the bodybuilding table export? Should be the same: table, id, date, weight

The Cardio export reads:
table, id, date, exercice, duration, distance, profil_id
So there is a spelling mistake:
exercice -> exercise

**Comment by alextsakpinis** [comment]
Since I am already familiar with the topic of exports I would continue with that issue. Is that ok for you?

**Comment by brodeurlv** [comment]
Hi Alex, this one is more complicated than it seems. Changing the column name will break the compatibility of old exports. 
Also, I would like to change all the mechanism of export to have something more robust and also something that can export the images as well in order to be abe to share exercise library with others but maybe that's a completely different feature (#79). I'm not yet clear on this. 
And then, I'm working on the migration to scoped storage so I am changing some stuff regarding the file access so it would be preferable to wait for this before changing anything to this, else, I'm not sure the merge will be easy. 
I will let you know when I'm done. Thanks.

**Comment by alextsakpinis** [comment]
I thought about loosing the combability with older versions when changing the column names and wanted to discuss that with you. But your answer already explained everything really well. I will then look for another open issue.
