### ISSUE TITLE
The app crashes when trying to display a graph Maximum (reps >=5), if there isn’t any

### ISSUE THREAD

**Issue by nmarkuks18** [brodeurlv/fastnfitness#50]
Found in version: 0.15.3

Current behavior: In the Graphs tab in Body Building page: When choosing an exercise which has less than five reps from the drop-down list and selecting display option Maximum (reps >=5), the app crashes. 

Expected behavior: Displays empty graph.

Step to reproduce:
1)	Body building page: create a new exercise or choose one from the list, insert less than 5 reps and press ‘Add’. 
2)	Go to the Graphs tab, select the exercise you added from the drop-down list
3)	Select Maximum (reps >=5) option from the display drop-down list.

**Comment by brodeurlv** [comment]
Hi, 
Thank you for your feedback.

Hum, that's strange! I'm not able to reproduce the crash on my side. I would say that there is indeed an issue because it is displaying a graph even if there is less that 5 records but not crashing.

Anyway, I can fix this and this will surely fix your issue as well. 
I will include it in the next release. 


Which version of Android do you use ?

**Comment by brodeurlv** [comment]
My bad. I finally succeed to reproduce it. I will fix that.
thanks

**Comment by nmarkuks18** [comment]
No worries, and sorry for the delay, github is having some issues today..

I’m able to reproduce the crashing every time I do those steps and before I reported it, I asked my friend to download the app and try the same steps to see if that happens to him too, and it does - just to make sure it’s not only because of my old android. So, my android version is 6.0.1 and my friend’s 8.0.0.

For me (and my friend) it works like this: If u have selected an exercise that has less than 5 reps and go to the graphs tab everything is fine at first, but immediately when u change the display to >= 5 reps, the app throws me out and i get an error message that says the app is stopped.

**Comment by brodeurlv** [comment]
it fixed.
thank you for rising this issue. 
will be in the next release.
