### ISSUE TITLE
Unable to create a profile

### ISSUE THREAD

**Issue by vlamacko** [brodeurlv/fastnfitness#60]
At the end of the introductory slideshow the user is prompted to create a profile. I am unable to create one because the entire form is unresponsive. The buttons can't be clicked and the text field can't be activated.

I have tested this with same result using the Google Play version, F-Droid version and the GitHub latest release apk.

**Comment by brodeurlv** [comment]
Oh, that's ugly ! 
Can you please give me more info on your phone ? Android version, Phone version, ....
Can you also snapshot the freezing screen ?
Thank you very much for rising this bug. I will try to fix it asap if I can reproduce it.

**Comment by brodeurlv** [comment]
One more question, are you able to set the birthday date ?

**Comment by brodeurlv** [comment]
Can you try this pre-release and tell me if it fix your issue ?
https://github.com/brodeurlv/fastnfitness/releases/download/0.17.1/app-release.apk
Thanks.

**Comment by vlamacko** [comment]
The prerelease seems to have fixed everything, including the birthday picker.

Thanks!

I am using Mi A2 Lite with Android 9.

**Comment by brodeurlv** [comment]
Great ! thank you for your help !
