### ISSUE TITLE
Add seconds unit for static exercises

### ISSUE THREAD

**Issue by GrantMoyer** [brodeurlv/fastnfitness#61]
Current behavior: Only lbs and kg are available as units

Expected behavior: lbs, kg, and s, available as units

This would allow tracking exercises such as static hangs.

**Comment by brodeurlv** [comment]
Hi GrantMoyer, 
Good idea! Thinking about it, I would propose more to create a new type of exercise close to bodybuilding one, but changing "Reps" by "Seconds". 
So you would have 
Series - Seconds - Weight

Sometimes you might want to do static hangs with additional weight so it would be better to keep it.

What do you think ?
Thanks for your feedback.

**Comment by GrantMoyer** [comment]
Given that number of repetitions makes no sense for static exercises, I think your suggestion is the right way to implement static exercise support.

However, it also has implications for the graph screen. Currently, reps aren't graphed, but instead used as a filter for what data to graph. So, whereas for repetition exercises, you plot the maximum weight lifted for greater than N reps, for static exercises, you'd be plotting the maximum weight held for greater than N seconds. With the current setup, you wouldn't be able to plot the duration of static holds over time.

If this feature were generalized to, for instance, distance for weighted running, it would also not be possible to plot distance over time.

Therefore, I'd propose also updating the graph screen to be able to “transpose” measurements. You should be able to plot maximum reps at a given weight in addition to maximum weight at a give rep count and so on for other exercises types.

**Comment by brodeurlv** [comment]
WIll be available in 0.18. Thanks.
