### ISSUE TITLE
FFMI as alternative to BMI

### ISSUE THREAD

**Issue by RayVermilion** [brodeurlv/fastnfitness#62]
Hi,
thanks for your work, the app does look really great so far.
I recommend to use the formula for the Fat free mass index (FFMI) as an alternative (maybe via spinner) to the current BMI.
As for Bodybuilders that would make more sense.

You can find the formula here 
https://goodcalculators.com/ffmi-fat-free-mass-index-calculator/

An even mire detailed report you can find here
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3306818/?report=classic
Best regards

**Comment by brodeurlv** [comment]
Nice idea. I was thinking also about RFM calculation, but it requires more work. 
For FFMI, I don't know this one. Thank you for letting me know. It should be simple to add. I will make it available in the next release. 
Thanks.
Best regards,

**Comment by brodeurlv** [comment]
Added in 0.17.3.
