### ISSUE TITLE
Contributor's guidelines & a formal privacy policy.

### ISSUE THREAD

**Issue by HarryHeights** [brodeurlv/fastnfitness#64]
Hello, I'm Harry. I engage in content creation for open source software. I mostly just create documents which I think would be valuable to the project. I'd like to contribute to yours by creating a contributor's guidelines, and make your privacy policy statement more formal. What do you think?

**Comment by brodeurlv** [comment]
Hi @HarryHeights 

I would love to have you contribute to the project. Can you give me more details on what would be on the contributor guidelines ? Do you have any example ?
And for the privacy policy also. Don't hesitate to make a pull request and I will review it. 

Thank you @HarryHeights .

**Comment by HarryHeights** [comment]
I'll send a pull request for the privacy policy. But, I need a few information, about third-party libraries. 

Here's a sample contributor's guidelines [here](https://github.com/hanjoongcho/aaf-easydiary/blob/master/Contributing.md)

**Comment by brodeurlv** [comment]
Ok. Regarding the third party, you should have almost everything here : 
https://github.com/brodeurlv/fastnfitness/blob/master/app/src/main/java/com/easyfitness/AboutFragment.java

Let me know if you need something else.
