### ISSUE TITLE
App crashed after clearing data by resetting the app and re-using the app

### ISSUE THREAD

**Issue by cckole** [brodeurlv/fastnfitness#65]
***Found in version***: 0.17.2

### Current behavior:

I reset the application to delete all my data in order to start afresh, but after resetting it, few touches on the app made it to crash.

### Expected behavior:
I expected the app to work just as it does when I first installed and start using it.

### Step to reproduce:
- Launch the app

- Create a profile

- Click on the three dots(menu) by the top right side 

- Click on reset application.

- Confirm the action by clicking yes (the app will close)

- Launch it again and choose a profile name by typing it on the provided space and click OK
- Start clicking on any feature to perform any action. The app will crash.

### Reproducing the bug
ttps://youtu.be/DylK0MwbYQs

###Additional description

After the crash, it works well without crashing anymore but each time I reset and start afresh, it always welcome me with a crash before working as expected.

**Comment by brodeurlv** [comment]
Hi @cckole , 

Thank you for this report. It's so cool to have a recording of the issue !
I'll work on it this week end and I'll let you know.
