### ISSUE TITLE
Offering Proofreading skills 

### ISSUE THREAD

**Issue by chrisbarth01** [brodeurlv/fastnfitness#69]
Hello, my name is Christopher Bartholomew, I love contributing to open source softwares. Normally, I often promote open source softwares by writing a blog post about them. However, I also want to be offering my proofreading skills to open source softwares. So I'd love to contribute to your project by proofreading any content which you want me to proofread. I also intend to hear from you.

**Comment by brodeurlv** [comment]
Hi Chris, thank you for the offering. I will let you know if I need any proofread. 
Thanks.
