### ISSUE TITLE
Add Reminder Feature

### ISSUE THREAD

**Issue by adewararilwan** [brodeurlv/fastnfitness#72]
Components
My suggestion is on the
-  Setting  Interface

### Proposal
> Fast N Fitness allows you to track your workout quickly and easily.

Adding a new feature will improve the application and the feature includes:
#### Reminder
 I suggest the addition of a new feature “Reminder”. It will be a very good idea when users are being reminded of fitness training every day from their mobile phones. In cases where the user of Fast N Fitness have forgotten to train for the day.  It could be that the user has a  busy schedule for the day but since the user always has the intention to training every day. The user could, therefore, set a reminder which will be a particular time he or she will train that it won't fall during the busy time.

##  <center>MOCKUP EXAMPLE</center>
![Reminder.jpg](https://cdn.steemitimages.com/DQmZsEPx4AdzZSLiQnKw6ER2xyBSMsaJaRyYk27vnsrqmTZ/Reminder.jpg)
The image above shows how the reminder feature will look like when implemented that will allow users to choose a preferred time that they want the application to remind them of fitness training.

## Benefit
*Reminder -* 
This will be a very important feature that will improve the application.  Looking at it from this point of angle, as a businessman I deal not only with business but also focus on how I could always get fit in order to be able to withstand many heavy activities in order not to breakdown easily after a heavy work rate. Then I work on my fitness to keep the strong mentality going.  I could, therefore, be very busy throughout the day and ending up not getting fitness training that day.  Getting the "Fast N Fitness" fitness tracking application could be helpful in the way that when it pops up as a reminder at my own convenient time which I have already set it to be. It will remind me to take fitness training and it will be very helpful than when having an alarm for that. A human could be so funny and lazy whereas we even keep shut the alarm when it rings but seeing the reminder from the Fast n Fitness application could serve as motivation where we could be reminded of having our training before embarking on our daily job.
This depends on the user convenient time at which time he or she has set the reminder.

## Conclusion
The Fast N Fitness application will get more and increased adoption if the proposed features are implemented. They will definitely increase the application user base and improve the application as a whole.

## MY GITHUB PROFILE:
https://github.com/adewararilwan

**Comment by brodeurlv** [comment]
Hi @adewararilwan , thank you for the details request. I agree it could be good to have this kind of reminder. Compared to all the other topics I have in mind, it is pretty low in priority. However, if you want to develop it and make a pull request, I will integrate it with pleasure. 
Best regards, 
Charles

**Comment by brodeurlv** [comment]
HI @adewararilwan, I won't move forward with this feature. I'm closing this issue. If ever you want to develop it, please feel free. Thanks.
