### ISSUE TITLE
Import of CSV files lead to incorrect dates.

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#74]
Found in version: 0.18 downloaded from F-droid.

Current behavior: exported records, reset application, created new profile, import records. Exercises are visible but dates are shifted, exercises done one july 2 are now listed as done on july 1. When I check the csv files they seem to be correct.

Expected behavior: after import I would expect the correct dates to be shown.

Step to reproduce: see above.

**Comment by WO15** [comment]
Did review the issue in more detail, seems not to be a default shift in dates, but due to fact that 1 did have exercises on June 30, and july 2, but NOT on July 1. The exercises of July 2 (date on which I made the export and import). Are shifted (shown in app) to July 1.

**Comment by brodeurlv** [comment]
Do you have the CSV file you used to reproduce the issue? Thanks.

**Comment by WO15** [comment]
EF_xx_Cardio_2019_07_02_13_22_28.csv
table,id,date,time,machine,duration,distance,profil_id
EFfontes,45,2019-07-02,,rowing,0,0.5,2
EFfontes,39,2019-07-01,,rowing,0,0.5,2
EFfontes,27,2019-06-28,,rowing,0,2.0,2
EFfontes,16,2019-06-25,,rowing,0,0.5,2
EFfontes,5,2019-06-22,,rowing,0,1.5,2
EFfontes,4,2019-06-22,,rowing,0,0.5,2
EFfontes,3,2019-06-21,,rowing,0,0.5,2

**Comment by WO15** [comment]
EF_xx_Exercises_2019_07_02_13_22_28.csv
table,id,name,description,type,bodyparts,favorites
EFmachines,4,biceps,,0,,false
EFmachines,6,crunch,,0,,false
EFmachines,5,lateral raise deltoids,,0,,false
EFmachines,9,plank,,2,,false
EFmachines,7,push-up,,0,,false
EFmachines,3,rowing,,1,,false
EFmachines,8,side crunch,,0,,false
EFmachines,10,sit-up,,0,,false
EFmachines,2,triceps,,0,,false
