### ISSUE TITLE
Import of body weight measurements from exported csv files seems not to work.

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#75]
Found in version: 0.18 downloaded from F-droid.

Current behavior: exported records, reset application, created new profile, import records. After importing EF_xx_BodyMeasures_xxxx file. App indicates that import is successful.  I would expect the weight measurements to be visible under the Weight Track menu item. However this is not the case. When you check the EF_xx_BodyMeasures_xxxx.csv file it does contain the correct data, 

Expected behavior: after import I would expect the registered weights to be visible.

Step to reproduce: see above.

**Comment by brodeurlv** [comment]
Fixed
