### ISSUE TITLE
App crashed during import of records if incorrect order of importing files is used.

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#76]
Found in version: 0.18 downloaded from F-droid.

Current behavior: exported records, reset application, created new profile, import records. If you import e.g. EF_xx_BodyBuilding_xxx.csv before first importing EF_xx_Exercises_xxx.csv the app crashes.

Expected behavior: create an error message. Something like "Import error: First import the file EF_xx_Exercises_2019_07_xxx.csv"

Step to reproduce: see above.

**Comment by brodeurlv** [comment]
With last commit, if one exercise doesn't exist then the import is cancelled. 
I've also added a little warning on the import dialog. It is not the best solution, but for now, it does the job. 
Thanks for submitting this issue.

**Comment by brodeurlv** [comment]
Fixed
