### ISSUE TITLE
Time on which an excersise is performed is not inclded in exported CSV-files

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#77]
Found in version: 0.18 downloaded from F-droid.

Current behavior: When you use "export records"  several .CSV files are created. In the files containing the exercises the date on which the exercise is performed is listed however the time is missing. In the app the time is listed as hh:mm:ss. When you use these files e.g. for import the time is also missing.

Expected behavior: .CSV files should contain all relevant data the app stores about exercises.

Step to reproduce: see above.

**Comment by brodeurlv** [comment]
Fixed in last commit.
