### ISSUE TITLE
Feature request: Training plan/schedule

### ISSUE THREAD

**Issue by t-8ch** [brodeurlv/fastnfitness#82]
It would be nice to be able to create predefined sets of exercises to represent training plans.

Possible features:
* Prefill number of sets, repetitions and weight from last record (maybe only from same training plan) for easier 
* multiple separate day-plans per plan

**Comment by brodeurlv** [comment]
HI @t-8ch, 
I agree with you. I have already started something in that direction but it is a major change in the app so it will take a little bit of time.

**Comment by senpl** [comment]
Any progress on that. I would like that feature. Maybe even could build some scratch version of it.
