### ISSUE TITLE
Make it possible to log duration for cardio excersises with more precision (add seconds)

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#83]
Found in version: 0.18.1 downloaded from F-droid

Current behavior: for exercises marked as Cardio you can indicate the distance and the duration. For duration you can select hours and minutes. For e.g. rowing this is often not precise enough. It would be better to also add seconds so hh:mm:ss. The speed shown in the graphs menu becomes also more precise then.

Expected behavior: see above.

Step to reproduce: See above.

**Comment by brodeurlv** [comment]
You're absolutly right. I'll see what I can do.
