### ISSUE TITLE
Google Play Services make 0.18.3 incompatible with F-Droid

### ISSUE THREAD

**Issue by relan** [brodeurlv/fastnfitness#84]
Found in version: 0.18.3

Current behavior: build.gradle includes [com.google.gms:google-services](https://github.com/brodeurlv/fastnfitness/blob/0.18.3/build.gradle#L15).

Expected behavior: no proprietary bits.

Step to reproduce: n/a.

F-Droid requires apps in its main repo to be 100% free (libre) software. Google Play Services libraries are proprietary.

If I understand correctly, you want to add crash reporting. I can recommend [ACRA](https://github.com/ACRA/acra) for that (F-Droid client uses it). It's free software and you can configure it to open an email client with the crash log when a crash happens, thus avoiding the Internet permission in your app.

**Comment by brodeurlv** [comment]
Hi @relan , 

Thanks for letting me know. For now I will just remove the Google play services. I'll see later for ACRA.
Best regards,

**Comment by relan** [comment]
Thanks! F-Droid will pick up 0.18.4 automatically.
