### ISSUE TITLE
Make changing values in workout menu more easy.

### ISSUE THREAD

**Issue by WO15** [brodeurlv/fastnfitness#86]
Found in version: 0.18.4 downloaded from F-droid.

Current behavior:
When you select an exercise in the Workout menu, the previously used values (sets, reps etc) are displayed. This is very good and convenient. However if you want to change these values you need to tap the value once to select and clear it, and a second time to open the numeric keyboard to type a new value. Not a big issue but would be nice if, with the first tap, the current value is deleted and the keyboard is opened at the same time so you can enter a new value, this saves one "screen-tap".
Expected behavior:
see above
Step to reproduce:
see above

**Comment by brodeurlv** [comment]
Hi @WO15, 
I have identified a fix for this. It will be in the next release. 
Thanks
