### ISSUE TITLE
Add Weight Track data (fat/muscles/water) optionally as kg, not as %

### ISSUE THREAD

**Issue by vanous** [brodeurlv/fastnfitness#91]
When adding measurement records, some scales provide absolute values (in kg) rather then percentage. It would be nice to enter these in kg and have the app to calculate the %.

Found in version: 0.18.5

Current behavior: measures entered as %

Expected behavior: optionally enter absolute weight

Thank you

**Comment by vanous** [comment]
Hmm, please scratch that, i will blame this on my bad sight, rather then my dementia :). my scale provides %, as expected...

**Comment by brodeurlv** [comment]
Ah ah! I love your comment! Thank you for the correction!
