### ISSUE TITLE
Adding new type of exercises brings keyboard to type text over the list of muscles checkboxes

### ISSUE THREAD

**Issue by sebadamus** [brodeurlv/fastnfitness#92]
Found in version:0.18.5

Current behavior:
There appears the list of muscles checkboxes to select, you select one, then go back or hide Google keyboard and no muscle is selected instead an empty textbox where you can write anything

Expected behavior:
Each muscle with a checbox

Step to reproduce:
Used to work fine on android 7, now on 9 seems to have some problems, when you select the muscle checkbox to add a new exercise kind it wont save it, instead you can type any text and then it cant be used as an exercise.  Will try to add a github issue later.

**Comment by sebadamus** [comment]
Here more data... (will try to translate to english because my app appears in spanish)
1, left side menu, click on Excercises
2, add
3, type of excercise? (Three buttons, cardio,static,culturism) I select culturism.
4, no you see Excercise and History, down of it the imagen (this time empty because its new)
And down of it tree lines to complete Name, Description, Muscles.
5, I complete Name: Test Name, Description: Test Desc... and after you click Muscles it opens a list of checkboxes where you can select several muscles at once, but this lists ALSO opens the keyboard to write text and it covers the lower part of the muscles lists where are the Cancel and Accept buttons.
(I could get them turning my phone horizontally or trying to make a screenshot this way the keyboard (google keyboard stantard) go hidden.  So then I can check for i.e. two boxes Bíceps and Tríceps and click Accept.
6, now it comes back to screen in point 4 but completed with what you select.  The strange thing is that the Muscles last line contains textually "Bíceps;Tríceps"

I might think that there is the problem, there should appear a lists of fixed muscles like options and not let you type text manually.

Hope to be clear, if you need some screenshot I can try...

**Comment by brodeurlv** [comment]
Hi @sebadamus, 
I have committed a fix so that the Text cannot be edited manually. 
Please reopen this issue if even it is not fixed in the 0.18.6.
Thanks
