### ISSUE TITLE
openScale for body weight/fat/muscle/water tracking

### ISSUE THREAD

**Issue by nxxxse** [brodeurlv/fastnfitness#97]
In the FOSS Android world, I see [openScale](https://github.com/oliexdev/openScale) as the best option currently. Maybe it would make sense to integrate with that instead of developing the same once again?

Waistline is going into this direction for example: https://github.com/davidhealey/waistline/pull/119

Opinions?

**Comment by brodeurlv** [comment]
Thank you for the feedback. To be honest, I don't really like the complexity of openScale and I don't plan to add this in the app. Thank you anyway for taking the time to open this issue.

**Comment by nxxxse** [comment]
You are welcome. From a user perspective, I don’t think openScale is so complex. I think that tracking for example body measurements with a tape measure provides useful insights. On the other hand, I don’t care about all this smart device integration like Bluetooth scales if that is what you mean I am on the same page as you. But I don’t mind having this feature as long as I don‘t have to use it.
