### ISSUE TITLE
Feature request: Skinfolds section

### ISSUE THREAD

**Issue by JPH89** [brodeurlv/fastnfitness#98]
In my opinion, it would be really nice to have another section on the left menu about [Skinfolds](https://exrx.net/Testing/BodyCompSites).

It could be exactly as the *Body Track* section but with the 7 skinfold sites from the previous link.

Finally, it would be amazing if the app could directly apply the [Skinfold formula to obtain the body fat %](https://exrx.net/Calculators/BodyComp) and add it to the *Weight Track* section.

**Comment by brodeurlv** [comment]
Hi @JPH89, 

I never heard about skinflods before. That's interresting but not something I'm planning to add to the app. That would require huge amount of work for few users. Hope you understand.
