### ISSUE TITLE
Feature Request: Preloading Common Exercises

### ISSUE THREAD

**Issue by BeatLink** [brodeurlv/fastnfitness#99]
It would be cool if the app could be preloaded with some common exercises as well as instructions on how to perform them or even gifs demonstrating them

**Comment by brodeurlv** [comment]
Hi @BeatLink, that's indeed something I would like to do in the app. This topic has already been raised in #79. I'm closing this issue to keep only one item per subject. Thanks anyway for the valuable suggestion.
